//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_prog_3_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajos
    {
        public int trabajo_id { get; set; }
        public string ubicacion { get; set; }
        public string posicion { get; set; }
        public string compañia { get; set; }
    }
}
